# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fdK7emIbiJIjJ9CBNP9fQDHmiAyJ4BV
"""

from dash import Dash, dcc, html, Input, Output
import plotly.express as px
import pandas as pd

data = [
    [1930, "Uruguay", "Argentina"],
    [1934, "Italy", "Czechoslovakia"],
    [1938, "Italy", "Hungary"],
    [1950, "Uruguay", "Brazil"],
    [1954, "Germany", "Hungary"],
    [1958, "Brazil", "Sweden"],
    [1962, "Brazil", "Czechoslovakia"],
    [1966, "United Kingdom", "Germany"],
    [1970, "Brazil", "Italy"],
    [1974, "Germany", "Netherlands"],
    [1978, "Argentina", "Netherlands"],
    [1982, "Italy", "Germany"],
    [1986, "Argentina", "Germany"],
    [1990, "Germany", "Argentina"],
    [1994, "Brazil", "Italy"],
    [1998, "France", "Brazil"],
    [2002, "Brazil", "Germany"],
    [2006, "Italy", "France"],
    [2010, "Spain", "Netherlands"],
    [2014, "Germany", "Argentina"],
    [2018, "France", "Croatia"],
    [2022, "Argentina", "France"]
]

df = pd.DataFrame(data, columns=["Year", "Winner", "Runner_Up"])

win_count = df["Winner"].value_counts().reset_index()
win_count.columns = ["Country", "Wins"]

fig = px.choropleth(
    win_count,
    locations="Country",
    locationmode="country names",
    color="Wins",
    color_continuous_scale="Blues",
    title="Number of World Cup Wins by Country"
)

app = Dash(__name__)
server = app.server

app.layout = html.Div([
    html.H1("World Cup Dashboard", style={'textAlign': 'center'}),

    dcc.Graph(figure=fig),

    html.Div([
        html.Label("Select a Year:", style={"fontSize":18}),
        dcc.Slider(
            id="year-slider",
            min=df["Year"].min(),
            max=df["Year"].max(),
            step=None,
            value=df["Year"].min(),
            marks={year: str(year) for year in df["Year"]}
        ),
        html.Div(id='result-display', style={'marginTop': '20px', 'fontSize': '20px'})
    ], style={'width':'80%', 'margin':'auto'})
])

@app.callback(
    Output('result-display', 'children'),
    Input('year-slider', 'value')
)
def display_result(year):
    row = df[df["Year"] == year].iloc[0]
    return f"The winner of the {year} World Cup was {row['Winner']} and the runner-up was {row['Runner_Up']}."


if __name__ == '__main__':
    app.run(debug=False, host='0.0.0.0', port=8000)